## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Stori Wyllt"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Bringing nature to life with wildlife ID, habitat creation & storytelling workshops"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/naturceredigion/storiwyllt.cymru"
  email = "hi@storiwyllt.cymru"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
